# Generated by Django 5.2.5 on 2025-09-03 13:04

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=128, verbose_name='Отдел')),
                ('employee_count', models.IntegerField(default=0, verbose_name='Количество сотрудников')),
                ('approve_employee_works', models.BooleanField(default=False, verbose_name='Одобрить рабочих дней сотрудников')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='info.factory', verbose_name='Фабрика')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отдели',
                'db_table': 'departments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Обновлено')),
                ('full_name', models.CharField(max_length=128, verbose_name='Ф.И.О.')),
                ('report_card', models.IntegerField(blank=True, null=True, verbose_name='Табель №')),
                ('employment_date', models.DateField(blank=True, null=True, verbose_name='Дата приема')),
                ('dismissal_date', models.DateField(blank=True, null=True, verbose_name='Дата увольнения')),
                ('fired', models.BooleanField(blank=True, default=False, null=True, verbose_name='Уволен')),
                ('black_listed', models.BooleanField(default=False, verbose_name='В черном списке')),
                ('black_listed_reason', models.TextField(blank=True, null=True, verbose_name='Причина черного списка')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('position_last_updated', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Адрес')),
                ('gender', models.SmallIntegerField(verbose_name='Пол')),
                ('passport_id', models.CharField(blank=True, max_length=9, null=True, verbose_name='№ и серия паспорта')),
                ('issued_by', models.CharField(blank=True, max_length=256, null=True, verbose_name='Кем выдан')),
                ('issued_date', models.DateField(blank=True, null=True, verbose_name='Когда выдан')),
                ('pinfl', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='PIN физического лица')),
                ('finger1', models.TextField(blank=True, null=True, verbose_name='Отпечаток пальца')),
                ('finger2', models.TextField(blank=True, null=True, verbose_name='Доп.отпечаток пальца')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='UZ', verbose_name='Телефон')),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True, verbose_name='Доп номер телефона')),
                ('badge', models.CharField(blank=True, max_length=128, null=True, unique=True, verbose_name='№ бейджика')),
                ('telegram_id', models.BigIntegerField(default=0, verbose_name='Номер телеграма')),
                ('ptr', models.IntegerField(default=0, verbose_name='ID турникет (GATE)')),
                ('can_delete_sock_package', models.BooleanField(default=False, verbose_name='Может удалить упаковок носков')),
                ('imported', models.BooleanField(default=False, verbose_name='Импортирован из другой системы')),
                ('additional_role', models.SmallIntegerField(blank=True, choices=[(0, '-----------'), (1, 'Модель носков'), (2, 'Склад'), (3, 'Модель одежди'), (4, 'ТБ'), (5, 'Модель носков материал'), (6, 'Модель носков аксессуар')], default=0, null=True, verbose_name='Дополнительное правило')),
                ('face', models.TextField(blank=True, null=True, verbose_name='Лицо')),
                ('one_c_deprtment_id', models.IntegerField(blank=True, null=True, verbose_name='ID отдела на 1C')),
                ('one_c_deprtment_name', models.CharField(blank=True, max_length=512, null=True, verbose_name='Название отдела на 1C')),
                ('one_c_sync_error_log', models.TextField(blank=True, editable=False, null=True, verbose_name='Лог синхронизации')),
                ('one_c_registered', models.BooleanField(default=False, verbose_name='Регистрирован в 1С')),
                ('is_iron_book', models.BooleanField(default=False, verbose_name='Темир дафтар')),
                ('exclude_attendance_auto_block', models.BooleanField(default=False, verbose_name='Исключать авто блокирование входа')),
                ('password_date', models.DateField(blank=True, null=True, verbose_name='Последняя изменение пароля')),
                ('need_password_change', models.BooleanField(default=False, verbose_name='Требуется изменение пароля')),
                ('working_hours', models.FloatField(blank=True, null=True, verbose_name='Количество рабочих часов')),
                ('working_days', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(7)], verbose_name='Количество рабочих дней')),
                ('access_control_factories', models.ManyToManyField(blank=True, related_name='attendance_access_employees', to='info.factory', verbose_name='Фабрики для доступа')),
                ('additional_factories', models.ManyToManyField(blank=True, related_name='additional_employees', to='info.factory', verbose_name='Дополнительные фабрики')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personals', to='hr.department', verbose_name='Департамент')),
                ('factory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='info.factory', verbose_name='Фабрика')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='info.uploadedimage')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='info.process', verbose_name='Процесс')),
                ('process_roles', models.ManyToManyField(blank=True, related_name='employees', to='info.processrole', verbose_name='Роли процессов')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'db_table': 'employee',
                'managed': True,
            },
        ),
    ]
