# Generated by Django 5.2.5 on 2025-09-03 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
        ('info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, verbose_name='Код')),
                ('name', models.CharField(max_length=32, verbose_name='Наименование')),
                ('price', models.FloatField(default=0, null=True, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Категория модель',
                'verbose_name_plural': 'Категории моделы',
                'db_table': 'category_model',
            },
        ),
        migrations.CreateModel(
            name='SewingFabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Тип полотна')),
            ],
            options={
                'verbose_name': 'Тип полотна',
                'verbose_name_plural': 'Типы полотна',
                'db_table': 'sewing_fabric_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SewingPackingPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Наименования')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цена упаковка одежда',
                'verbose_name_plural': 'Цены упаковка одежди',
            },
        ),
        migrations.CreateModel(
            name='SewingPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Названия части')),
            ],
            options={
                'verbose_name': 'Часть одежды',
                'verbose_name_plural': 'Части одежды',
                'db_table': 'sewing_parts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransferPrintPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Наименования')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Цена трансферной печати',
                'verbose_name_plural': 'Цены трансферной печати',
            },
        ),
        migrations.CreateModel(
            name='SewingFabric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Полотно')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sewing.sewingfabrictype', verbose_name='Тип полотна')),
            ],
            options={
                'verbose_name': 'Полотно',
                'verbose_name_plural': 'Полотна',
                'db_table': 'sewing_fabric',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SewingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Линия')),
                ('worker_count', models.IntegerField(default=25, verbose_name='Вмесимость работников')),
                ('ordering', models.IntegerField(default=0, verbose_name='По очереди')),
                ('status', models.BooleanField(default=True, verbose_name='Статус')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sewing_lines', to='hr.department', verbose_name='Отдел')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sewing_lines', to='info.factory', verbose_name='Фабрика')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='hr.employee', verbose_name='Мастер')),
            ],
            options={
                'verbose_name': 'Линия швейки',
                'verbose_name_plural': 'Линии швейки',
                'db_table': 'sewing_lines',
            },
        ),
        migrations.CreateModel(
            name='SewingProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Обновлено')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование модели')),
                ('vendor_code', models.CharField(max_length=128, verbose_name='Артикул')),
                ('season', models.CharField(blank=True, default='', max_length=32, verbose_name='Сезон')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Скидка, %')),
                ('cutting_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Крой')),
                ('transfer_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Трансфер')),
                ('print_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Печать')),
                ('embroidery_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Вышивка')),
                ('sewing_loss_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Потеря швейки, %')),
                ('other_expenses_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Прочие расходы, %')),
                ('profitability', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Рентабельность, %')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Комиссия, %')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_model', to='sewing.categorymodel', verbose_name='Категория')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='info.uploadedimage')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
            ],
            options={
                'verbose_name': 'Модель одежды',
                'verbose_name_plural': 'Модели одежды',
                'db_table': 'sewing_product_model',
            },
        ),
        migrations.CreateModel(
            name='ModelVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Обновлено')),
                ('kind', models.CharField(choices=[('marketing', 'Маркетинг'), ('sample', 'Образец'), ('planned', 'Плановый')], db_index=True, default='marketing', max_length=16, verbose_name='Тип варианта')),
                ('name', models.CharField(max_length=128, verbose_name='Названия')),
                ('loss', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Угар, %')),
                ('design_code', models.CharField(blank=True, max_length=128, null=True, verbose_name='Код дизайна')),
                ('cloned', models.BooleanField(default=False, verbose_name='Клон')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Подробно')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена за изделие')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
                ('work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_variants', to='info.worktype', verbose_name='Вид работы')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='sewing.sewingproductmodel')),
            ],
            options={
                'verbose_name': 'Вариант модели',
                'verbose_name_plural': 'Варианты модели',
                'db_table': 'variants',
            },
        ),
        migrations.CreateModel(
            name='VariantAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Обновлено')),
                ('count', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена (за изделие)')),
                ('local_produce', models.BooleanField(default=False, verbose_name='Производство')),
                ('notes', models.CharField(blank=True, default='', max_length=512, verbose_name='Примечание')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_accessories', to='info.material', verbose_name='Аксессуар')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='sewing.modelvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Аксессуар варианта',
                'verbose_name_plural': 'Аксессуары варианта',
                'db_table': 'sewing_variant_accessories',
            },
        ),
        migrations.CreateModel(
            name='VariantMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Обновлено')),
                ('count', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('packing_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Рулон'), (2, 'Пачка'), (3, 'Раскрытий')], null=True, verbose_name='Вид упаковки')),
                ('width', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Ширина')),
                ('height', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Высота')),
                ('density', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Плотность')),
                ('loss', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Потеря, %')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена (за изделие)')),
                ('main', models.BooleanField(default=False, verbose_name='Основной')),
                ('notes', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='Примечание')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='info.color', verbose_name='Цвет')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sewing_variants', to='info.material', verbose_name='Материал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
                ('used_parts', models.ManyToManyField(blank=True, to='sewing.sewingpart', verbose_name='Использованные части')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='sewing.modelvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Материал варианта',
                'verbose_name_plural': 'Материалы варианта',
                'db_table': 'sewing_variant_materials',
            },
        ),
        migrations.CreateModel(
            name='VariantOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Обновлено')),
                ('seconds', models.PositiveIntegerField(default=0, verbose_name='Расход времени')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Цена за операцию')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.operation', verbose_name='Операция')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='sewing.modelvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Операция варианта',
                'verbose_name_plural': 'Операции варианта',
                'db_table': 'sewing_variant_operation',
                'constraints': [models.UniqueConstraint(fields=('variant', 'operation'), name='uniq_operation_per_variant')],
            },
        ),
        migrations.CreateModel(
            name='VariantSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Обновлено')),
                ('notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Примечание')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.size', verbose_name='Размер')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='sewing.modelvariant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Размер варианта',
                'verbose_name_plural': 'Размеры варианта',
                'db_table': 'sewing_variant_sizes',
                'constraints': [models.UniqueConstraint(fields=('variant', 'size'), name='uniq_size_per_variant')],
            },
        ),
    ]
