# Generated by Django 5.2.5 on 2025-09-04 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('sewing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvariant',
            name='work_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_variants', to='info.worktype', verbose_name='Вид работы'),
        ),
    ]
