# Generated by Django 5.2.5 on 2025-09-04 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('sewing', '0002_alter_modelvariant_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvariant',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='model_variants', to='info.worktype', verbose_name='Вид работы'),
        ),
        migrations.AlterField(
            model_name='variantmaterial',
            name='loss',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Потеря Материала, %'),
        ),
        migrations.AlterField(
            model_name='variantmaterial',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена (за 1 kg)'),
        ),
    ]
