# Generated by Django 5.2.5 on 2025-09-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewing', '0003_alter_modelvariant_work_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantmaterial',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена (за 1 кг)'),
        ),
    ]
