# Generated by Django 5.2.5 on 2025-09-09 13:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_material_mat_title_trgm_material_mat_code_trgm'),
        ('sewing', '0004_alter_variantmaterial_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SewingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Обновлено')),
                ('shipment_date', models.DateField(blank=True, null=True, verbose_name='Дата отгрузки')),
                ('order_type', models.CharField(choices=[('sample', 'Образец'), ('production', 'Производство'), ('marketing', 'Маркетинг'), ('other', 'Другое')], default='production', max_length=20, verbose_name='Тип заказа')),
                ('status', models.IntegerField(choices=[(1, 'Новый'), (3, 'В работе'), (4, 'Готов'), (5, 'Отменён'), (6, 'В разработке'), (7, 'На согласовании'), (8, 'Подтверждён'), (9, 'Прерван'), (10, 'Принят')], db_index=True, default=1, verbose_name='Статус')),
                ('total_qty', models.PositiveIntegerField(default=0, verbose_name='Итого кол-во')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Итого сумма')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sewing_orders_buyer', to='info.firm', verbose_name='Покупатель')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кем создано')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sewing_orders_customer', to='info.firm', verbose_name='Заказчик')),
                ('specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sewing_orders', to='info.specification', verbose_name='Спецификация')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)ss', to=settings.AUTH_USER_MODEL, verbose_name='Кем обновлено')),
            ],
            options={
                'verbose_name': 'Швейный заказ',
                'verbose_name_plural': 'Швейные заказы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SewingOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кол-во')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Цена за единицу')),
                ('status', models.IntegerField(choices=[(1, 'Новый'), (3, 'В работе'), (4, 'Готов'), (5, 'Отменён'), (6, 'В разработке'), (7, 'На согласовании'), (8, 'Подтверждён'), (9, 'Прерван'), (10, 'Принят')], db_index=True, default=1, verbose_name='Статус позиции')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sewing.sewingorder', verbose_name='Заказ')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='sewing.modelvariant', verbose_name='Вариант модели')),
            ],
            options={
                'verbose_name': 'Позиция заказа',
                'verbose_name_plural': 'Позиции заказа',
                'ordering': ('pk',),
            },
        ),
        migrations.AddIndex(
            model_name='sewingorder',
            index=models.Index(fields=['status'], name='sewing_sewi_status_22ca78_idx'),
        ),
        migrations.AddIndex(
            model_name='sewingorder',
            index=models.Index(fields=['shipment_date'], name='sewing_sewi_shipmen_7ecf96_idx'),
        ),
        migrations.AddIndex(
            model_name='sewingorder',
            index=models.Index(fields=['order_type'], name='sewing_sewi_order_t_404fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='sewingorder',
            index=models.Index(fields=['customer'], name='sewing_sewi_custome_0f814a_idx'),
        ),
        migrations.AddIndex(
            model_name='sewingorder',
            index=models.Index(fields=['created_at'], name='sewing_sewi_created_7ad9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='sewingorderitem',
            index=models.Index(fields=['order'], name='sewing_sewi_order_i_95e10b_idx'),
        ),
        migrations.AddIndex(
            model_name='sewingorderitem',
            index=models.Index(fields=['variant'], name='sewing_sewi_variant_3e9957_idx'),
        ),
        migrations.AddIndex(
            model_name='sewingorderitem',
            index=models.Index(fields=['status'], name='sewing_sewi_status_963aa6_idx'),
        ),
    ]
