# Generated by Django 5.2.5 on 2025-09-10 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_material_mat_title_trgm_material_mat_code_trgm'),
        ('sewing', '0005_sewingorder_sewingorderitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SewingOrderSizeCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_counts', to='sewing.sewingorderitem')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.size')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'size'), name='uniq_item_size')],
            },
        ),
    ]
