# Generated by Django 5.2.5 on 2025-09-09 13:44

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='material',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='mat_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='material',
            index=django.contrib.postgres.indexes.GinIndex(fields=['code'], name='mat_code_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
